# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/parameters

[environments.dev]
url = "jdbc:sqlserver://golem.csse.rose-hulman.edu;databaseName=FinalProject_S3G3;encrypt=false"

[flyway]
locations = ["filesystem:migrations"]
